spring:
  application:
    name: campaign-management

  datasource:
    url: jdbc:mysql://localhost:3306/campaign?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: macerace120
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual   # manual ack for reliability
        prefetch: 1

  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword   # if set, warna remove karo
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 1000ms

  quartz:
    job-store-type: jdbc               # Production: DB mein persist hoga
    jdbc:
      initialize-schema: always        # Quartz tables auto-create karega
    properties:
      org.quartz:
        scheduler:
          instanceName: CampaignScheduler
          instanceId: AUTO           # Cluster ke liye AUTO
        jobStore:
          tablePrefix: QRTZ_
          isClustered: false         # Single node — true karo agar cluster ho
          clusterCheckinInterval: 10000
          useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 10            # 10 parallel jobs max
          threadPriority: 5
server:
  port: 8080